name: libclash_vpn_service
description: VPN service plugin for Clash Mi (reimplemented).
version: 0.12.15
homepage: https://github.com/clashmi
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LibclashVpnServicePlugin
      android:
        package: com.nebula.libclash_vpn_service
        pluginClass: LibclashVpnServicePlugin
      macos:
        pluginClass: LibclashVpnServicePlugin
