package libclash

import (
	"bytes"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// loadConfigData reads the main config and merges the optional patch files on
// top of it. The patch final file is generated by the client as JSON and has
// the highest priority.
func loadConfigData(options *StartOptions) ([]byte, error) {
	data, err := os.ReadFile(options.ConfigFile)
	if err != nil {
		return nil, fmt.Errorf("read config %s: %w", options.ConfigFile, err)
	}

	if options.ConfigFilePatch != "" {
		patchData, err := os.ReadFile(options.ConfigFilePatch)
		if err != nil {
			return nil, fmt.Errorf("read patch %s: %w", options.ConfigFilePatch, err)
		}
		data, err = mergeYAML(data, patchData)
		if err != nil {
			return nil, fmt.Errorf("merge patch: %w", err)
		}
	}

	if options.ConfigFilePatchFinal != "" {
		finalData, err := os.ReadFile(options.ConfigFilePatchFinal)
		if err != nil {
			return nil, fmt.Errorf("read patch final %s: %w", options.ConfigFilePatchFinal, err)
		}
		data, err = mergeYAML(data, finalData)
		if err != nil {
			return nil, fmt.Errorf("merge patch final: %w", err)
		}
	}

	return data, nil
}

// mergeYAML merges the override document into the base document recursively.
// Both documents may be YAML or JSON (JSON is a subset of YAML).
func mergeYAML(base, override []byte) ([]byte, error) {
	var baseMap map[string]any
	if err := yaml.Unmarshal(base, &baseMap); err != nil {
		return nil, err
	}
	var overrideMap map[string]any
	if err := yaml.Unmarshal(override, &overrideMap); err != nil {
		return nil, err
	}

	merged := mergeMaps(baseMap, overrideMap)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(merged); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func mergeMaps(base, override map[string]any) map[string]any {
	if base == nil {
		base = map[string]any{}
	}
	for key, value := range override {
		if sub, ok := value.(map[string]any); ok {
			if baseSub, ok := base[key].(map[string]any); ok {
				base[key] = mergeMaps(baseSub, sub)
			} else {
				base[key] = sub
			}
		} else {
			base[key] = value
		}
	}
	return base
}
