storePassword.debug=clashmi
keyPassword.debug=clashmi
keyAlias.debug=clashmi
storeFile.debug=../../private_for_build/clashmi/clashmi/android/sign/clashmi.release.keystore
   
storePassword.release=clashmi
keyPassword.release=clashmi
keyAlias.release=clashmi
storeFile.release=../../private_for_build/clashmi/clashmi/android/sign/clashmi.release.keystore
